### ISSUE TITLE
Does a `ToBorrowed` trait make sense?

### ISSUE THREAD

**Issue by jakoschiko** [fujiapple852/bounded-static#66]
From the perspective of symmetry it might make sense to have a trait like that:
```rust
trait ToBorrowed {
    type Borrowed<'a>;

    fn to_borrowed<'a>(&'a self) -> Self::Borrowed<'a>;
}
```
This would allow code like that:
```rust
use std::borrow::Cow;
use std::sync::atomic::{AtomicU64, Ordering};

use bounded_static::ToBorrowed; // Yeah, I know that this conflicts with the crate name :p

#[derive(ToBorrowed)]
enum Data<'a> {
    Blob(Cow<'a, [u8]>),
    Text(Cow<'a, str>),
}

#[derive(ToBorrowed)]
struct EnrichedData<'a> {
    id: u32,
    data: Data<'a>
}

fn main() {
    let data = Data::Blob(Cow::Owned(vec![1, 2, 3]));
    process(data.to_borrowed()); // Does not actually clone the content of `Data`
    process(data.to_borrowed()); // Can be called twice without cloning `Data`
}

fn process(data: Data<'_>) { // Takes ownership of `Data`, but not of its content
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let id = COUNTER.fetch_add(1, Ordering::Relaxed);
    let enriched_data = EnrichedData {
        id,
        data, // Would not work with `&Data<'_>`
    };
    process_enriched(enriched_data);
}

fn process_enriched(enriched_data: EnrichedData<'_>) {
    drop(enriched_data)
}
```
Does that makes sense? Did you consider adding something like that? Are you aware of any crate providing this?

**Comment by fujiapple852** [comment]
I think the `borrowme` crate may provide this functionality?  I haven’t used that crate personally but I recall when it was [announced](https://www.reddit.com/r/rust/s/ikOB1EVtJb) there were some cases it couldn’t handle which this crate can, I don’t know if that has been fixed. 

As to adding similar functionality to this crate, I’m not opposed to the idea and indeed I think this crate is poorly named anyway and so is hard to discover.  So perhaps some rebranding or a fork is required. 

do you have a specific use case in mind and is this something you’d be keen to work on?

**Comment by jakoschiko** [comment]
I do decoding/encoding. All involved structs and enums contain only `Copy` types or `Cow`-like types.

The decoders are zero-copy, so they take `&'a [u8]` and return something like `Foo<'a>`. If the user needs to get rid of the `'a` they can use `to_static` and get a `Foo<'static>` thanks to your crate. Everything is fine.

But what about the encoders? Ideally they don't take the ownership of the data because they only need to read it. An encoder would look like this:

```rust
// library code
pub fn encode_status<'a>(status: &Status<'a>, out: &mut [u8]) -> usize {
    todo!()
}
```

And then it can be used like this:

```rust
// user code
let status: Status<'static> = todo!();
let written_bytes = encode_status(&status, out);
```

But this strategy prevents me from doing other reasonable things, for example this:

```rust
// library code
enum Response<'a> {
    Status(Status<'a>)
    Data(Data<'a>)
}

pub fn encode_status<'a>(status: &Status<'a>, out: &mut [u8]) -> usize {
    let response = Response::Status(status); // Doesn't work because &Status<'a> is not Status<'a>
    encode_response(&response, write_buffer);
}

pub fn encode_data<'a>(data: &Data<'a>, out: &mut [u8]) -> usize {
    let response = Response::Data(data); // Doesn't work because &Data<'a> is not Data<'a>
    encode_response(&response, out);
}

pub fn encode_response<'a>(respose: &Response<'a>, out: &mut [u8]) -> usize {
    todo!()
}
```

How can this be solved? The first step is to get rid of the `&`:

```rust
// library code
pub fn encode_status<'a>(status: Status<'a>, out: &mut [u8]) -> usize {
    let response = Response::Status(status); // Yeah, it works
    encode_response(response, out);
}

pub fn encode_data<'a>(data: Data<'a>, out: &mut [u8]) -> usize {
    let response = Response::Data(data); // Yeah, it works
    encode_response(response, out);
}

pub fn encode_response<'a>(respose: Response<'a>, out: &mut [u8]) -> usize {
    todo!()
}
```

But the user should be able to decide whether they transfer ownership of the data to the encoder or not. For this I want to have a utility similar to `to_static`:

```rust
// user code
let status: Status<'static> = todo!();
// Not a real clone, more like a copy and the user keeps the ownership
let written_bytes = encode_status(status.to_borrowed(), out);
// The user transfers the ownership
let written_bytes = encode_status(status, out);
```

> I think the borrowme crate may provide this functionality?

Thanks! I'll have a look. My first impression: It creates many additional types that would clutter the API.

> and is this something you’d be keen to work on?

You mean by contributing? Sure. If we can resolve the naming issues and you can convince me that my idea is sane.

**Comment by jakoschiko** [comment]
I created the repo https://github.com/jakoschiko/cowabunga for outlining my idea. I had some initial problems with lifetimes but it seems to work now. What do you think?

**Comment by fujiapple852** [comment]
Thanks @jakoschiko - just a quick note to say that i'll try to dig into your repo this weekend and give you some thoughts.

**Comment by jakoschiko** [comment]
Thanks! Some relevant questions:

- Why has `bounded-static` multiple traits? What are the pros?
- Why has the associated type `Static` the bound `'static`? That might be problematic for exotic cases like `Cow<'a, [&'b Foo]>`.

**Comment by fujiapple852** [comment]
@jakoschiko apologies for the delay, i've been focusing on a release of another project.

> Why has bounded-static multiple traits? What are the pros?

I don't recall there being a major reason, I suppose you may have a type where you want to support either of `to_static(&self)` or `into_static(self)` but not both, but I can't think of any real world examples.  Is there any advantage in combining them?

> Why has the associated type Static the bound 'static?

That's really the whole point of this library, ensuring the type is bound by `'static`.  Without it you effectively just have [ToOwned](https://doc.rust-lang.org/std/borrow/trait.ToOwned.html).    See https://github.com/fujiapple852/bounded-static#how-does-this-differ-from-the-toowned-trait

> That might be problematic for exotic cases like Cow<'a, [&'b Foo]>

I think that is desirable; for `Cow<'a, T>` to be `Cow<'a, T>: 'static` then it follows that `T: 'static`.

In your example the reference `&'b` cannot be made static _for all_ lifetimes `'b`.  Aside: the fact that it `?Sized` is ok.

The derive macro specifically checks for this case: https://github.com/fujiapple852/bounded-static/blob/master/bounded-static-derive/src/common.rs#L31

**Comment by jakoschiko** [comment]
> apologies for the delay, i've been focusing on a release of another project.

No problem, take your time. This issue doesn't block me in any way.

> > Why has bounded-static multiple traits? What are the pros?
> 
> I don't recall there being a major reason, I suppose you may have a type where you want to support either of `to_static(&self)` or `into_static(self)` but not both, but I can't think of any real world examples. Is there any advantage in combining them?

Not sure yet. When I created my repo, providing and implementing only the single trait `Cowabunga` made it easier for me to understand what I was actually doing. It helped me that there is a similarity between the `Cowabunga` trait and `Cow` struct.

**Comment by jakoschiko** [comment]
> > Why has the associated type Static the bound 'static?
> 
> That's really the whole point of this library, ensuring the type is bound by `'static`. Without it you effectively just have [ToOwned](https://doc.rust-lang.org/std/borrow/trait.ToOwned.html). See https://github.com/fujiapple852/bounded-static#how-does-this-differ-from-the-toowned-trait

I can't follow your arguments. I don't want to use `std::borrow::ToOwned` because it requires that I provide two different types (like `str` and `String`). Instead I want an abstraction that simply allows me to convert all (deeply nested) `Cow` values inside my type to `Owned` (this is currently possible with your crate) and `Borrowed` (this is what I proposed in this issue). IMO the `'static` bound is unnecessarily restrictive for that.

Imagine you have a type that contains a `Cow` and a completely unrelated other reference:

```rust
struct FooBar<'foo, 'bar> {
    foo: Cow<'foo, str>,
    bar: &'bar str,
}
```
Then I don't see why this should not be allowed:
```rust
impl<'foo, 'bar> Cowabunga for FooBar<'foo, 'bar> {
    type Owned = FooBar<'static, 'bar>; // We can keep 'bar here because Owned does not require 'static

    type Borrowed<'b> = FooBar<'b, 'bar>
    where
        Self: 'b;

    fn to_borrowed<'b>(&'b self) -> Self::Borrowed<'b> {
        FooBar {
            foo: cowabunga::to_borrowed(&self.foo),
            bar: self.bar,
        }
    }

    fn to_owned(&self) -> Self::Owned {
        FooBar {
            foo: cowabunga::to_owned(&self.foo),
            bar: self.bar,
        }
    }

    fn into_owned(self) -> Self::Owned {
        FooBar {
            foo: cowabunga::into_owned(self.foo),
            bar: self.bar,
        }
    }
}
```

**Comment by fujiapple852** [comment]
Hi again @jakoschiko (and happy holidays!),

I think there are two separate goals here; one is to provide "a way to convert a type to a form that is bound by the `'static` lifetime, if possible" and the other is to provide "an abstraction that allows conversion of any deeply nested `Cow` values to the `Owned` variant" (to paraphrase your comment).

This crate is designed to provide a solution to meet the first goal, and as a (very useful!) side effect it _also_ provides a solution to meet the second goal, but only in conjunction with the first.  

What you need is a solution to meet the second goal _in isolation_.  That makes sense and is perfectly valid, but would seem to be at odds with the core purpose of the `bounded-static` crate as it would not ensure that types were indeed "bounded by the `'static` lifetime".  My original use care for creating this crate was the need to pass some highly nested `Cow` structure to `thread::spawn`, which requires the 'static bound.

Given this it would seem that a separate abstraction (or crate, such as `Cowabunga`) is warranted.

**Comment by jakoschiko** [comment]
Thanks for your analysis!

To be honest, even after thinking about it for a while I can't see the relevant differences between these goals. They sound different, but I don't understand the practical implications. I think the best way forward for me is to fork your repository and refactor it for my purpose. Then we can see if it's worth to be published as a separate crate. I'll close this issue because it probably don't make sense to add something like this to this crate here. Thanks again for your feedback.
